Repository telling-me/tellingme-iOS, pull requests merged in 2023-08, with the labels that each got.

#90 Feat/communication #89
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/1024.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/114.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/120.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/180.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/29.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/40.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/57.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/58.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/60.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/80.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/87.png
  TellingMe/tellingMe/app/globalData/Emotion.swift
  TellingMe/tellingMe/app/singleton/CommunicationData.swift
  TellingMe/tellingMe/data/auth/API/LoginAPI.swift
  TellingMe/tellingMe/data/auth/DTO/CheckNicknameDTO.swift
  TellingMe/tellingMe/data/auth/DTO/JobInfoDTO.swift
  TellingMe/tellingMe/data/auth/DTO/OauthDTO.swift
  TellingMe/tellingMe/data/auth/DTO/SignUpDTO.swift
  TellingMe/tellingMe/data/auth/DTO/WithdrawlDTO.swift
  TellingMe/tellingMe/data/base/ResponseData.swift
  TellingMe/tellingMe/data/communication/api/CommunicationAPI.swift
  TellingMe/tellingMe/data/communication/dto/CommunicationList.swift
  TellingMe/tellingMe/data/communication/dto/QuestionList.swift
  TellingMe/tellingMe/data/like/api/LikeAPI.swift
  TellingMe/tellingMe/data/like/dto/Like.swift
  TellingMe/tellingMe/presentation/answerCompleted/AnswerCompletedViewController.swift
  TellingMe/tellingMe/presentation/answerList/viewController/AnswerListViewController.swift
  TellingMe/tellingMe/presentation/common/header/BackHeaderView.swift
  TellingMe/tellingMe/presentation/common/question/QuestionView.swift
  TellingMe/tellingMe/presentation/communication/Communication.storyboard
  TellingMe/tellingMe/presentation/communication/repository/CommunicationListRepository.swift
  TellingMe/tellingMe/presentation/communication/repository/CommunicationRepository.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationDetailViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationPageViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunityViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationDetailViewModel.swift
  TellingMe/tellingMe/presentation/communication/views/CommunicationDetailCell.swift
  TellingMe/tellingMe/presentation/communication/views/CommunityCardView.swift
  TellingMe/tellingMe/presentation/communication/views/QuestionCollctionViewCell.swift
  TellingMe/tellingMe/presentation/communication/views/SortHeaderView.swift
  TellingMe/tellingMe/presentation/home/viewController/HomeViewController.swift
  TellingMe/tellingMe/presentation/setting/Setting.storyboard
  TellingMe/tellingMe/util/extension/Array+.swift
  TellingMe/tellingMe/util/extension/UIViewController+.swift
Labels: style, feat

#94 [#93] feat : communication answer view & reportView
  TellingMe/Podfile
  TellingMe/Podfile.lock
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/svg/button/etc/siren.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/button/etc/siren.imageset/Siren.svg
  TellingMe/tellingMe/Assets.xcassets/svg/button/gif/Contents.json
  TellingMe/tellingMe/data/answer/API/AnswerAPI.swift
  TellingMe/tellingMe/data/base/MoyaProvider+.swift
  TellingMe/tellingMe/data/like/dto/LikeDTO.swift
  TellingMe/tellingMe/data/question/DTO/QuestionDTO.swift
  TellingMe/tellingMe/data/report/api/ReportAPI.swift
  TellingMe/tellingMe/data/report/dto/ReportDTO.swift
  TellingMe/tellingMe/presentation/answer/repository/ModifyAnswerRepository.swift
  TellingMe/tellingMe/presentation/answerCompleted/AnswerCompletedRepository.swift
  TellingMe/tellingMe/presentation/answerList/AnswerList.storyboard
  TellingMe/tellingMe/presentation/answerList/viewController/AnswerListViewController.swift
  TellingMe/tellingMe/presentation/common/answer/AnswerTextView.swift
  TellingMe/tellingMe/presentation/common/bottomSheet/BottomSheet.swift
  TellingMe/tellingMe/presentation/common/emotion/EmotionView.swift
  TellingMe/tellingMe/presentation/common/header/BackHeaderView.swift
  TellingMe/tellingMe/presentation/common/header/MainHeaderView.swift
  TellingMe/tellingMe/presentation/common/question/QuestionView.swift
  TellingMe/tellingMe/presentation/communication/Communication.storyboard
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationAnswerViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationDetailViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunityViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/ReportViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationAnswerViewModel.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationListViewModel.swift
  TellingMe/tellingMe/presentation/communication/viewModel/ReportViewModel.swift
  TellingMe/tellingMe/presentation/communication/views/CommunityCardView.swift
  TellingMe/tellingMe/presentation/communication/views/ReportCollectionViewCell.swift
  TellingMe/tellingMe/presentation/home/Home.storyboard
  TellingMe/tellingMe/presentation/home/repository/HomeRepository.swift
  TellingMe/tellingMe/presentation/home/viewController/HomeViewController.swift
  TellingMe/tellingMe/util/extension/UIViewController+.swift
Labels: refac, feat

#96 Feedback/fixes 1 #95
  .gitignore
  TellingMe/Podfile
  TellingMe/Podfile.lock
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/1024.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/114.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/120.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/180.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/29.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/40.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/57.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/58.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/60.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/80.png
  TellingMe/tellingMe/Assets.xcassets/AppIcon.appiconset/87.png
  TellingMe/tellingMe/app/AppDelegate.swift
  TellingMe/tellingMe/data/answer/API/AnswerAPI.swift
  TellingMe/tellingMe/data/communication/api/CommunicationAPI.swift
  TellingMe/tellingMe/data/user/api/UserAPI.swift
  TellingMe/tellingMe/document/badWords.txt
  TellingMe/tellingMe/font/NanumSquareRoundOTFB.otf
  TellingMe/tellingMe/font/NanumSquareRoundOTFEB.otf
  TellingMe/tellingMe/font/NanumSquareRoundOTFL.otf
  TellingMe/tellingMe/font/NanumSquareRoundOTFR.otf
  TellingMe/tellingMe/presentation/answer/viewModel/AnswerViewModel.swift
  TellingMe/tellingMe/presentation/answerList/AnswerList.storyboard
  TellingMe/tellingMe/presentation/answerList/viewController/AnswerListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationAnswerViewModel.swift
  TellingMe/tellingMe/presentation/communication/views/CommunityCardView.swift
  TellingMe/tellingMe/presentation/home/Home.storyboard
  TellingMe/tellingMe/presentation/home/repository/PushNotificationModalRepository.swift
  TellingMe/tellingMe/presentation/home/viewController/PushNotificationModalViewController.swift
  TellingMe/tellingMe/presentation/home/viewModel/PushNotificationViewModel.swift
  TellingMe/tellingMe/presentation/setting/Setting.storyboard
  TellingMe/tellingMe/presentation/setting/main/repository/SettingRepository.swift
  TellingMe/tellingMe/presentation/setting/main/viewController/SettingTableViewController.swift
  TellingMe/tellingMe/presentation/setting/main/viewModel/SettingViewModel.swift
  TellingMe/tellingMe/presentation/signUp/SignUp.storyboard
  TellingMe/tellingMe/presentation/signUp/SignUpViewController.swift
  TellingMe/tellingMe/presentation/signUp/page/AgreementDetailViewController.swift
  TellingMe/tellingMe/presentation/signUp/page/AgreementViewController.swift
  TellingMe/tellingMe/presentation/signUp/page/GetOptionViewController.swift
  TellingMe/tellingMe/presentation/signUp/page/page+/PageViewModel.swift
  TellingMe/tellingMe/presentation/splash/Splash.gif
  TellingMe/tellingMe/presentation/splash/Splash.json
  TellingMe/tellingMe/presentation/splash/Splash.mp4
  TellingMe/tellingMe/presentation/splash/Splash.storyboard
  TellingMe/tellingMe/presentation/splash/SplashViewController.swift
  TellingMe/tellingMe/presentation/splash/repository/SplashRepository.swift
  TellingMe/tellingMe/trash/PushNotificationModalRepository.swift
Labels: refac, feat, feedback

#98 [#97] feature: likes
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/svg/button/gif/Contents.json
  TellingMe/tellingMe/app/singleton/CommunicationData.swift
  TellingMe/tellingMe/data/answer/API/AnswerAPI.swift
  TellingMe/tellingMe/data/base/MoyaProvider+.swift
  TellingMe/tellingMe/data/communication/api/CommunicationAPI.swift
  TellingMe/tellingMe/data/communication/dto/CommunicationList.swift
  TellingMe/tellingMe/data/like/api/LikeAPI.swift
  TellingMe/tellingMe/data/like/dto/LikeDTO.swift
  TellingMe/tellingMe/data/user/api/UserAPI.swift
  TellingMe/tellingMe/presentation/answerList/repository/AnswerListRepository.swift
  TellingMe/tellingMe/presentation/answerList/viewController/AnswerListViewController.swift
  TellingMe/tellingMe/presentation/answerList/viewModel/AnswerListViewModel.swift
  TellingMe/tellingMe/presentation/communication/Communication.storyboard
  TellingMe/tellingMe/presentation/communication/repository/CommunicationListRepository.swift
  TellingMe/tellingMe/presentation/communication/repository/CommunicationRepository.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationAnswerViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationDetailViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationPageViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunityViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationAnswerViewModel.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationListViewModel.swift
  TellingMe/tellingMe/presentation/communication/views/CommunicationDetailCell.swift
  TellingMe/tellingMe/presentation/communication/views/LikeButton.swift
  TellingMe/tellingMe/presentation/communication/views/SortHeaderView.swift
  TellingMe/tellingMe/presentation/signUp/SignUpViewController.swift
  TellingMe/tellingMe/presentation/signUp/page/page+/PageViewModel.swift
Labels: style, feat

#102 모두의 공간에서 생겼던 피드백과 오류를 수정했습니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/app/singleton/CommunicationData.swift
  TellingMe/tellingMe/data/answer/DTO/TodayAnswerDTO.swift
  TellingMe/tellingMe/presentation/answerList/view/CardListCollectionViewCell.swift
  TellingMe/tellingMe/presentation/answerList/viewController/CardListCollectionViewController.swift
  TellingMe/tellingMe/presentation/common/emotion/EmotionView.swift
  TellingMe/tellingMe/presentation/common/header/BackHeaderView.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationAnswerViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationDetailViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationPageViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationAnswerViewModel.swift
  TellingMe/tellingMe/presentation/communication/views/CommunicationDetailCell.swift
  TellingMe/tellingMe/presentation/communication/views/CommunityCardView.swift
  TellingMe/tellingMe/presentation/home/Home.storyboard
  TellingMe/tellingMe/presentation/home/viewController/PushNotificationModalViewController.swift
  TellingMe/tellingMe/presentation/home/viewModel/PushNotificationViewModel.swift
  TellingMe/tellingMe/presentation/setting/main/viewModel/SettingViewModel.swift
  TellingMe/tellingMe/presentation/signUp/SignUp.storyboard
  TellingMe/tellingMe/util/extension/UIViewController+.swift
Labels: refac, feedback

#104 회원가입시 생기는 오류사항을 수정하였습니다.
  TellingMe/tellingMe/data/base/MoyaProvider+.swift
  TellingMe/tellingMe/presentation/answer/viewController/AnswerViewController.swift
  TellingMe/tellingMe/presentation/answerCompleted/AnswerCompletedViewController.swift
  TellingMe/tellingMe/presentation/common/modal/Modal.storyboard
  TellingMe/tellingMe/presentation/common/modal/ModalViewController.swift
  TellingMe/tellingMe/presentation/home/viewController/PushNotificationModalViewController.swift
  TellingMe/tellingMe/presentation/setting/main/viewController/SettingTableViewController.swift
  TellingMe/tellingMe/presentation/setting/main/viewController/WithdrawalViewController.swift
  TellingMe/tellingMe/presentation/setting/main/viewModel/SettingViewModel.swift
  TellingMe/tellingMe/presentation/setting/myInfo/viewController/MyInfoViewController.swift
  TellingMe/tellingMe/presentation/signUp/SignUp.storyboard
  TellingMe/tellingMe/presentation/signUp/page/GetPurposeController.swift
Labels: refac, hotFix

#107 나의 공간 & 모두의 공간에서 생기는 스크롤 효과를 수정하였습니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/presentation/answerList/AnswerList.storyboard
  TellingMe/tellingMe/presentation/answerList/view/CardListCollectionViewCell.swift
  TellingMe/tellingMe/presentation/answerList/viewController/CardListCollectionViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/Communication.storyboard
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationListViewModel.swift
Labels: feedback

#108 SPM 으로 전환했고, 최소 OS 버전을 16.0 으로 올렸으며, AlarmView Data 중 API 와 DTO 를 추가했습니다.
  TellingMe/.swiftlint.yml
  TellingMe/Podfile
  TellingMe/Podfile.lock
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TellingMe/tellingMe.xcworkspace/contents.xcworkspacedata
  TellingMe/tellingMe.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TellingMe/tellingMe/data/alarm/api/AlarmAPI.swift
  TellingMe/tellingMe/data/alarm/dto/AlarmDTO.swift
  TellingMe/tellingMe/data/mypage/api/MyPageAPI.swift
  TellingMe/tellingMe/data/mypage/dto/MyPageDTO.swift
  TellingMe/tellingMe/presentation/alarm/viewControllers/AlarmViewController.swift
  TellingMe/tellingMe/presentation/alarm/viewModel/AlarmViewModel.swift
  TellingMe/tellingMe/presentation/alarm/views/AlarmTableViewCell.swift
  TellingMe/tellingMe/presentation/signUp/SignUpViewController.swift
  TellingMe/tellingMe/util/custom/style/structs/ProgressBar.swift
  TellingMe/tellingMe/util/extension/UIFont+.swift
  TellingMe/tellingMe/util/extension/UIStackView+.swift
  TellingMe/tellingMe/util/extension/UIView+.swift
  TellingMe/tellingMe/util/nameSpace/Color+.swift
  TellingMe/tellingMe/util/nameSpace/CustomFont.swift
Labels: bug, style, refac, feat, feedback

#111 알림창 뷰를 모두 구현했습니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/svg/button/etc/readAllDIsabled.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/button/etc/readAllDIsabled.imageset/readAllDIsabled.svg
  TellingMe/tellingMe/Assets.xcassets/svg/button/etc/readAllEnabled.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/button/etc/readAllEnabled.imageset/readAllEnabled.svg
  TellingMe/tellingMe/data/alarm/api/AlarmAPI.swift
  TellingMe/tellingMe/presentation/alarm/viewControllers/AlarmViewController.swift
  TellingMe/tellingMe/presentation/alarm/viewModel/AlarmViewModel.swift
  TellingMe/tellingMe/presentation/alarm/views/AlarmNavigationBarView.swift
  TellingMe/tellingMe/presentation/alarm/views/AlarmReadAllSectionView.swift
  TellingMe/tellingMe/presentation/alarm/views/AlarmTableViewCell.swift
  TellingMe/tellingMe/presentation/common/header/CustomNavigationBarView.swift
  TellingMe/tellingMe/presentation/common/header/MainHeaderView.swift
  TellingMe/tellingMe/presentation/home/viewController/HomeViewController.swift
  TellingMe/tellingMe/presentation/home/viewModel/HomeViewModel.swift
  TellingMe/tellingMe/util/extension/String+.swift
  TellingMe/tellingMe/util/extension/UIFont+.swift
  TellingMe/tellingMe/util/nameSpace/Color+.swift
  TellingMe/tellingMe/util/nameSpace/CustomFont.swift
Labels: feat

#118 홈 뷰의 새로고침과 탭바의 색상이 깨지는 버그를 Fix 했습니다.
  TellingMe/tellingMe/presentation/home/repository/HomeRepository.swift
  TellingMe/tellingMe/presentation/tab/MainTabBarController.swift
Labels: bug, hotFix

#116 라이브러리 뷰를 구현하였습니다.
  .gitignore
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TellingMe/tellingMe/Assets.xcassets/svg/images/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/images/LibraryItem1.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/images/LibraryItem1.imageset/Group 301 (1).svg
  TellingMe/tellingMe/Assets.xcassets/svg/images/LibraryItem2.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/images/LibraryItem2.imageset/Group 300.svg
  TellingMe/tellingMe/presentation/answer/viewController/EmotionViewController.swift
  TellingMe/tellingMe/presentation/common/dropdown/DropDownButton.swift
  TellingMe/tellingMe/presentation/common/header/InlineHeaderView.swift
  TellingMe/tellingMe/presentation/library/temp/Library.storyboard
  TellingMe/tellingMe/presentation/library/temp/LibraryNavigationViewController.swift
  TellingMe/tellingMe/presentation/library/viewControllers/LibraryViewController.swift
  TellingMe/tellingMe/presentation/library/viewModel/LibraryViewModel.swift
  TellingMe/tellingMe/presentation/library/views/DividerFooterView.swift
  TellingMe/tellingMe/presentation/library/views/LibraryCollectionViewCell.swift
  TellingMe/tellingMe/presentation/library/views/LibraryInfoCollectionViewCell.swift
  TellingMe/tellingMe/presentation/library/views/LibraryInfoView.swift
  TellingMe/tellingMe/presentation/library/views/WeekHeaderView.swift
  TellingMe/tellingMe/presentation/login/repository/LoginRepository.swift
  TellingMe/tellingMe/presentation/signUp/SignUp.storyboard
  TellingMe/tellingMe/presentation/splash/Splash.storyboard
  TellingMe/tellingMe/presentation/tab/MainTabBar.storyboard
  TellingMe/tellingMe/util/collectionViewLayout/HorizontalHeaderCollectionViewFlowLayout.swift
  TellingMe/tellingMe/util/collectionViewLayout/LeftAlignedCollectionViewFlowLayout.swift
  TellingMe/tellingMe/util/extension/Array+.swift
  TellingMe/tellingMe/util/nameSpace/Color+.swift
  TellingMe/tellingMe/util/nameSpace/Emotions.swift
Labels: style, feat

#114 알림창 뷰의 UI 버그와 기능 버그를 Fix 했습니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/data/alarm/api/AlarmAPI.swift
  TellingMe/tellingMe/data/alarm/dto/AlarmDTO.swift
  TellingMe/tellingMe/presentation/alarm/viewControllers/AlarmViewController.swift
  TellingMe/tellingMe/presentation/alarm/viewModel/AlarmViewModel.swift
  TellingMe/tellingMe/presentation/alarm/views/AlarmTableViewCell.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationListViewModel.swift
  TellingMe/tellingMe/presentation/myPage/viewControllers/MyPageViewController.swift
  TellingMe/tellingMe/presentation/myPage/viewModel/MyPageViewModel.swift
  TellingMe/tellingMe/presentation/myPage/views/MyPageBoxView.swift
  TellingMe/tellingMe/presentation/myPage/views/MyPageHeaderView.swift
  TellingMe/tellingMe/presentation/myPage/views/MyPageProfileView.swift
  TellingMe/tellingMe/presentation/myPage/views/components/MyPageMainIconView.swift
  TellingMe/tellingMe/presentation/myPage/views/components/MyPageTableViewCell.swift
Labels: bug, refac, feat
