Repository telling-me/tellingme-iOS, pull requests merged in 2023-10, with the labels that each got.

#149 온보딩에서 일어나는 앱 크래시 버그를 핫픽스합니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/presentation/home/REF_viewControllers/HHomeViewController.swift
  TellingMe/tellingMe/presentation/home/REF_views/HomeHoverView.swift
  TellingMe/tellingMe/presentation/home/REF_views/HomeQuestionView.swift
  TellingMe/tellingMe/presentation/login/viewController/OnBoardingViewController.swift
  TellingMe/tellingMe/presentation/myPage/views/MyPageProfileView.swift
  TellingMe/tellingMe/util/managers/AnalyzeManager.swift
Labels: bug, feedback, hotFix

#150 [#147] fix/1.1.1version QA
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/Group 310.svg
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/온보딩1_1x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/온보딩1_2x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/온보딩1_3x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/Frame 496.svg
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/온보딩2_1x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/온보딩2_2x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/온보딩2_3x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/Group 313.svg
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/온보딩3_1x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/온보딩3_2x.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/온보딩3_3x 1.png
  TellingMe/tellingMe/app/singleton/CommunicationData.swift
  TellingMe/tellingMe/data/auth/api/SignAPI.swift
  TellingMe/tellingMe/data/user/dto/MyInfoRepository.swift
  TellingMe/tellingMe/presentation/answerList/view/CardListCollectionViewCell.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/Communication.storyboard
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationDetailViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationListViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunicationPageViewController.swift
  TellingMe/tellingMe/presentation/communication/viewControllers/CommunityViewController.swift
  TellingMe/tellingMe/presentation/communication/viewModel/CommunicationListViewModel.swift
  TellingMe/tellingMe/presentation/login/Login.storyboard
  TellingMe/tellingMe/presentation/login/repository/LoginRepository.swift
  TellingMe/tellingMe/presentation/login/viewController/LoginViewController.swift
  TellingMe/tellingMe/presentation/login/viewController/SignInViewController.swift
  TellingMe/tellingMe/presentation/login/viewModel/LoginViewModel.swift
  TellingMe/tellingMe/presentation/login/viewModel/SignInViewModel.swift
  TellingMe/tellingMe/presentation/login/views/SocialLoginButton.swift
  TellingMe/tellingMe/presentation/myPage/setting/Setting.storyboard
  TellingMe/tellingMe/presentation/myPage/setting/main/repository/SettingRepository.swift
  TellingMe/tellingMe/presentation/myPage/setting/main/view/SettingTableViewCell.swift
  TellingMe/tellingMe/presentation/myPage/setting/main/viewController/SettingTableViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/main/viewController/SettingViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/main/viewController/WithdrawalViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/main/viewModel/SettingViewModel.swift
  TellingMe/tellingMe/presentation/myPage/setting/myInfo/viewController/ChipGenderViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/myInfo/viewController/ChipJobViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/myInfo/viewController/ChipPurposeViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/myInfo/viewController/MyInfoViewController+.swift
  TellingMe/tellingMe/presentation/myPage/setting/myInfo/viewController/MyInfoViewController.swift
  TellingMe/tellingMe/presentation/myPage/setting/myInfo/viewModel/MyInfoViewModel.swift
  TellingMe/tellingMe/presentation/myPage/viewControllers/MyPageViewController.swift
  TellingMe/tellingMe/presentation/signUp/viewModel/SignUpViewModel.swift
  TellingMe/tellingMe/presentation/splash/repository/SplashRepository.swift
  TellingMe/tellingMe/trash/LoginViewController.swift
  TellingMe/tellingMe/trash/page/page+/PageViewModel.swift
  TellingMe/tellingMe/trash/repository/LoginRepository.swift
Labels: refac, hotFix

#154 Plus 유저를 위한 글자수 500 개 및 감정을 추가합니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/presentation/answer/Answer.storyboard
  TellingMe/tellingMe/presentation/answer/viewController/AnswerViewController+.swift
  TellingMe/tellingMe/presentation/answer/viewController/AnswerViewController.swift
  TellingMe/tellingMe/presentation/answer/viewController/EmotionViewController.swift
  TellingMe/tellingMe/presentation/answer/viewController/ModifyAnswerViewController.swift
  TellingMe/tellingMe/presentation/answer/viewModel/AnswerViewModel.swift
  TellingMe/tellingMe/presentation/answer/viewModel/EmotionViewModel.swift
  TellingMe/tellingMe/presentation/answerList/AnswerList.storyboard
  TellingMe/tellingMe/presentation/home/viewControllers/HomeViewController.swift
  TellingMe/tellingMe/presentation/home/viewModels/HomeViewModel.swift
  TellingMe/tellingMe/presentation/home/views/HomeHeaderView.swift
  TellingMe/tellingMe/presentation/home/views/HomeHoverView.swift
  TellingMe/tellingMe/presentation/home/views/HomePushNotificationPopUpView.swift
  TellingMe/tellingMe/presentation/home/views/HomeQuestionView.swift
  TellingMe/tellingMe/presentation/home/views/question/HomeQuestionBoxView.swift
  TellingMe/tellingMe/presentation/home/views/question/HomeSubDateView.swift
  TellingMe/tellingMe/presentation/home/views/question/HomeWritingButton.swift
  TellingMe/tellingMe/presentation/secure/controllers/SecurityViewController.swift
  TellingMe/tellingMe/presentation/secure/viewModels/SecurityViewModel.swift
  TellingMe/tellingMe/presentation/secure/views/securityView.swift
  TellingMe/tellingMe/presentation/tab/MainTabBarController.swift
  TellingMe/tellingMe/util/managers/IAPManager.swift
Labels: feat

#158 회원가입 성별 오류를 수정하였습니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/온보딩1_1x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/온보딩1_2x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding1.imageset/온보딩1_3x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/온보딩2_1x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/온보딩2_2x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding2.imageset/온보딩2_3x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/Contents.json
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/온보딩3_1x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/온보딩3_2x 1.png
  TellingMe/tellingMe/Assets.xcassets/svg/sign/onBoarding/OnBoarding3.imageset/온보딩3_3x 2.png
  TellingMe/tellingMe/keyChain/StringLiteral.swift
  TellingMe/tellingMe/presentation/signUp/viewModel/SignUpViewModel.swift
Labels: hotFix

#160 Trash 폴더를 한 번 비우고자 합니다.
  TellingMe/tellingMe.xcodeproj/project.pbxproj
  TellingMe/tellingMe/trash/AllowNotificationViewController.swift
  TellingMe/tellingMe/trash/GetBirthdayViewController.swift
  TellingMe/tellingMe/trash/GetMBTIViewController.swift
  TellingMe/tellingMe/trash/GetMBTIViewModel.swift
  TellingMe/tellingMe/trash/LoginViewController.swift
  TellingMe/tellingMe/trash/PrivacyPolicyViewController.swift
  TellingMe/tellingMe/trash/PushNotificationModalRepository.swift
  TellingMe/tellingMe/trash/SignUpPageViewController.swift
  TellingMe/tellingMe/trash/SignUpRepository.swift
  TellingMe/tellingMe/trash/SignUpViewController2.swift
  TellingMe/tellingMe/trash/page/AgreementDetailViewController2.swift
  TellingMe/tellingMe/trash/page/AgreementViewController2.swift
  TellingMe/tellingMe/trash/page/GetJobViewController.swift
  TellingMe/tellingMe/trash/page/GetNameViewController.swift
  TellingMe/tellingMe/trash/page/GetOptionViewController.swift
  TellingMe/tellingMe/trash/page/GetPurposeController.swift
  TellingMe/tellingMe/trash/page/page+/JobTableViewCell.swift
  TellingMe/tellingMe/trash/page/page+/PageRepository.swift
  TellingMe/tellingMe/trash/page/page+/PageViewModel.swift
  TellingMe/tellingMe/trash/repository/AnswerListRepository.swift
  TellingMe/tellingMe/trash/repository/LoginRepository.swift
Labels: refac
